### ISSUE TITLE
Support webpack 5

### ISSUE THREAD

**Issue by Niznikr** [hipstersmoothie/react-docgen-typescript-plugin#30]
Relates to storybookjs/storybook#14118

Storybook has enabled experimental support for webpack5 in `6.2`. `react-docgen-typescript-plugin` does not seem to work properly with webpack 5 enabled.

**Comment by Niznikr** [comment]
Happy to test out to help confirm any proposed solutions 😄

**Comment by shilman** [comment]
Hey @hipstersmoothie! This issue is the biggest blocker on Storybook's move to webpack5 and we've called in the big guns, @bebraw, to help us with the upgrade. For simplicity, our current plan is a major version bump of this library that supports webpack5 and drops webpack4 support. We are also looking at a couple other stretch optimizations, and hope to have something working in the next couple weeks.

Does that all sound reasonable? Should we we create a PR to this repo, or would you rather we forked this into the Storybook org, since we're probably the biggest user of the library by far. We appreciate your tremendous work on getting this to where it is (and the rest of your contributions to Storybook!), and are happy to introduce the changes in whatever way you're comfortable with. Please let us know what works for you!

**Comment by 7rulnik** [comment]
@shilman seems that it could be webpack 4 compatible. I opened draft PR https://github.com/hipstersmoothie/react-docgen-typescript-plugin/pull/32/ based on https://github.com/storybookjs/storybook/issues/14118#issuecomment-802711917

I think that I can finish it on this weekend
